language: java
before_install:
- chmod +x gradlew
deploy:
  provider: heroku
  api_key:
    secure: lTBWXfaafO5dpH7FXN4UANtnrvRx+YUSNQ8BG3xDDPADCFVFWSrlCJ9EXZzFnsCUYXkuLBtdrl1vt3Bi6Cik3CV0e5/9tLKtrLUAr1cMw1KsABs+tagyohtLlqeEK5kf5+9CadP/xGniONI6LUrVbIj6wUpv3ORMxdSBJFBKKkQpO8TLINl0qVQL+1zyjrPXmvylDHQhYAiZkDfT6fyzYFafwaFHPKoJlRp4s3sp+h71J8BGiP5105MLy328l4ah5fmJe3wbGF+uOqXcUXCwOh+cDa25eZrhdwXPJu/2BCaGZlmGbVlvCg1JqYI2GWQAwZM+eDdLnNPLxQbqy7+IaIwDAK0s5zijzKtfK1ezIIbAoI4eROfF8TCeO94a+t+TO4odfxzJYOwyeadwpLKJcK1AP0PyF+LcPCoQK8OYXjVqEx3RZh2iOYF+IbOKNbSx4wHZOGftms/27zuKQ5NX/GKsHjc1i+ITS4xKTUOyml7+a4W0t/eJoVfcemLmfo3yaTLVUXW9z6AKS2DlTDSKoyPQTntUCFWcz4caoxVBDtRZUIvRhpBYpv23LL9kYyGCHUinjENPZrqpaP3GwYDISBe4sZ5zJOylvuOWFeCECFcxzF3WqjHth1TD1a9LTNLBUNwNBw8I7qUje+t2UkQm0EChkq4/Oqsj5I8sGUQKJok=
