language: java
before_install:
- chmod +x gradlew
deploy:
  provider: heroku
  api_key:
    secure: okb2PHZPOaVlb9g1EGNgVJ6ww3BzfPkc+uRbdZc5jtjklGXAHG3Cpl1QTy8ncHZZRkKOCkHYpdw0tHxF05IZmkSRLTLIDCvjwf0z09WFLASS6H4AtjLV7PHphcsxRR3Ge/X6JbQFBXiuFhyNUK9yylXv9fNe6r1WZ3h3pR+KMfD1RhjbL02L2Phsn7jqZpyHE5X/uEIEh/XC9jLvJiPcbFzrEq+Sq7Jskm0uFamN2azaveRYQ7w6vwk6ZLflQtkj8nRCuxWETBzNKoFErNjfPilpwk7jB6tJubz2MPj34xd5/79vmdpdfMbeIDxeoRYJYP0kiES9uUYDc+Ts3R00zV1DGTuyJaIYvbo9C0NjZjOZnyiHSyPSAZVIG3LKI4bIQ/Ip1c0OI9seNLlMI76p/NXD3LR68c3fGOQcCs2F5eICY9xYdWL7a4/d1z3mjnyhUczhjeFXddvPwRdi7N0aj08GXOzMurbGR8brBIMK4KM8+Ddt1brTu1PJTaMDmjKT6uj4hwU3bEve9NMLciyffjU+tNgHy9+btAvheWFG0jJpxDvMpnnpVSR3YbLi8lQqtYUT3e875t14SCUabnOXj9C0pXBq4MEYYUIJX0DBKOj2rK+QzUvFwbFET+woHLD6l2cfTKYQVeueSbr8XtUyHJQXrA7YWJnGOnW+P1soy9I=
